spring:
  application:
    name: dubbo-employee-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tbl?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      dialect:
      storage_engine: innodb
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
    open-in-view: false
dubbo:
  scan:
    base-packages: com.hdax.dubbo.employee.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
    group: hdax